apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: openshift-cluster-nfd-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/openshift-cluster-nfd-operator/openshift-cluster-nfd-operator@sha256:925f7ee125f1935c159480b176a5fefa64efd6c2fe8872b2cee5ed86fd828fb5
        name: container-image
        resources: {}
status: {}
